### ISSUE TITLE
How use this module

### ISSUE THREAD

**Issue by QPLAYid** [Xposed-Modules-Repo/me.hd.hookgg#3]
Any video or document ?

**Comment by HdShare** [comment]
1. Enable the HookGG module in LSPosed and set the module scope to GameGuardian
2. Set up the page in HookGG and configure the package name, type, and function
3. Start GameGuardian and execute the script, and you can see the relevant logs on the HookGG log page

**Comment by QPLAYid** [comment]
> 1. Enable the HookGG module in LSPosed and set the module scope to GameGuardian
> 2. Set up the page in HookGG and configure the package name, type, and function
> 3. Start GameGuardian and execute the script, and you can see the relevant logs on the HookGG log page

![Screenshot_2024-03-26-15-06-59-648_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/db023cf9-a1e7-4ba2-8b11-a7b61dc80df2)
![Screenshot_2024-03-26-15-08-13-766_com android shell](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/7e57dd6d-af74-4ae8-8743-cca114b122ee)

When i search value hook gg nit sned log

**Comment by HdShare** [comment]
The package name is the package name set to GameGuardian, not the game package name
For example, in the picture, you are com.cae or com.jyrhfdgpwrbqfcc
Logs are logs recorded by executing scripts, and it is not clear whether there are logs by simply searching for them

**Comment by QPLAYid** [comment]
> The package name is the package name set to GameGuardian, not the game package name For example, in the picture, you are com.cae or com.jyrhfdgpwrbqfcc Logs are logs recorded by executing scripts, and it is not clear whether there are logs by simply searching for them

![Screenshot_2024-03-26-15-33-46-554_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/5a9b41c8-3856-48a1-bfc8-be765518f830)


Still same when i research manual or run script emty logs

**Comment by QPLAYid** [comment]
> The package name is the package name set to GameGuardian, not the game package name For example, in the picture, you are com.cae or com.jyrhfdgpwrbqfcc Logs are logs recorded by executing scripts, and it is not clear whether there are logs by simply searching for them

![Screenshot_2024-03-26-15-36-58-868_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/82d7f561-1e23-496d-a9b4-4a314d082f0d)


Nah is work but 
Only search vakue edit ?

What about hook void ? Some script use that trick

And hexpatch

Gameguardian use method offset fir hex patch

Example 

Offset 
0x1234 
Hexoatch to fffffff

**Comment by HdShare** [comment]
Please give me a concrete script example

Here's the script I tested
![image](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/49312623/ac1bc7c7-cff5-4f48-9f9f-8c823ba7cfbd)

Logs generated by the module
![image](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/49312623/7b5542b4-ae68-4534-9bd5-fea91b67076b)

**Comment by QPLAYid** [comment]
> Please give me a concrete script example
> 
> Here's the script I tested ![image](https://private-user-images.githubusercontent.com/49312623/316754936-ac1bc7c7-cff5-4f48-9f9f-8c823ba7cfbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzYwMDUsIm5iZiI6MTcxMTQzNTcwNSwicGF0aCI6Ii80OTMxMjYyMy8zMTY3NTQ5MzYtYWMxYmM3YzctY2ZmNS00ZjQ4LTlmOWYtOGM4MjNiYTdjZmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA2NDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDBhMGY5YWYyOTVkYmEwZjMxY2EyOGQ3MjViN2ZlZDA5NTZiNGJlZTIxMzk3OGM1MGZiMDk5OGQyZjQzM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eSRp-SR9BXlha_93Cfg2fOZ0pvucjtAUIm_HKqeFbU0)
> 
> Logs generated by the module ![image](https://private-user-images.githubusercontent.com/49312623/316754996-7b5542b4-ae68-4534-9bd5-fea91b67076b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzYwMDUsIm5iZiI6MTcxMTQzNTcwNSwicGF0aCI6Ii80OTMxMjYyMy8zMTY3NTQ5OTYtN2I1NTQyYjQtYWU2OC00NTM0LTliZDUtZmVhOTFiNjcwNzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA2NDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZWNiZjQxNWY3ZWU2MjViZWM1NDQ2OGZiMDY2NTFjOThlN2Q1NzRiZTg2ZDA0MWQzMzQ0MzZmY2FkNTJkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C7VbK_kxJ47hW9knZpc5DmfCR5ea0JDf1aZmmcGLwt0)

You have telegram ?

**Comment by QPLAYid** [comment]
I will contack you

**Comment by QPLAYid** [comment]
> > Tolong beri saya contoh skrip konkret
> > Inilah skrip yang saya uji ![gambar](https://private-user-images.githubusercontent.com/49312623/316754936-ac1bc7c7-cff5-4f48-9f9f-8c823ba7cfbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzYwMDUsIm5iZiI6MTcxMTQzNTcwNSwicGF0aCI6Ii80OTMxMjYyMy8zMTY3NTQ5MzYtYWMxYmM3YzctY2ZmNS00ZjQ4LTlmOWYtOGM4MjNiYTdjZmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA2NDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDBhMGY5YWYyOTVkYmEwZjMxY2EyOGQ3MjViN2ZlZDA5NTZiNGJlZTIxMzk3OGM1MGZiMDk5OGQyZjQzM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eSRp-SR9BXlha_93Cfg2fOZ0pvucjtAUIm_HKqeFbU0)
> > Log dihasilkan oleh modul ![gambar](https://private-user-images.githubusercontent.com/49312623/316754996-7b5542b4-ae68-4534-9bd5-fea91b67076b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzYwMDUsIm5iZiI6MTcxMTQzNTcwNSwicGF0aCI6Ii80OTMxMjYyMy8zMTY3NTQ5OTYtN2I1NTQyYjQtYWU2OC00NTM0LTliZDUtZmVhOTFiNjcwNzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA2NDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZWNiZjQxNWY3ZWU2MjViZWM1NDQ2OGZiMDY2NTFjOThlN2Q1NzRiZTg2ZDA0MWQzMzQ0MzZmY2FkNTJkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C7VbK_kxJ47hW9knZpc5DmfCR5ea0JDf1aZmmcGLwt0)
> 
> Anda punya telegram ?

![Screenshot_2024-03-26-15-52-29-060_bin mt plus](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/f87c622a-d060-429d-b328-725ab586b7ab)

Like this one

**Comment by QPLAYid** [comment]
![Screenshot_2024-03-26-15-53-51-654_bin mt plus](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/c8a9bc6f-54f3-44f3-a1eb-1a5c3b100aec)

This one

**Comment by QPLAYid** [comment]
And this one 
https://youtu.be/zBGb7bfbLZU

File 
https://hackershouse.tech/method-patching-library-game-guardian

Document

https://hackershouse.tech/method-patching-library-game-guardian/void-hooking

**Comment by HdShare** [comment]
It seems that you can only hook getRangesList and return value

**Comment by QPLAYid** [comment]
> It seems that you can only hook getRangesList and return value

So can be log that ?

**Comment by HdShare** [comment]
> > 似乎只能挂钩getRangesList并返回值
> 
> 那么可以记录吗？

Not in the current version, it will be added in a later version

**Comment by QPLAYid** [comment]
> > > 似乎只能挂钩getRangesList并返回值
> > 
> > 
> > 那么可以记录吗？
> 
> Not in the current version, it will be added in a later version

I wil wiat for new update thanks
