### ISSUE TITLE
Need logs gameguardian use offset

### ISSUE THREAD

**Issue by QPLAYid** [Xposed-Modules-Repo/me.hd.hookgg#4]
Need logs gameguardian use hexpatch for offset

![Screenshot_2024-03-26-15-36-58-868_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/e14c3dc8-3499-47db-83e8-dbc8abd73d0b)

Cant log in when gameguardian use hexpatch for offset

**Comment by HdShare** [comment]
local addr_start = gg.getRangesList('lib.so')[0].start
local addr_edit = addr_start + 0x11223344
add = {}
add[1] = {}
add[1].address = addr_edit
add[1].flags = 4
add[1].value = 0
gg.setValues(add)

It seems that you can only hook getRangesList and return value

**Comment by QPLAYid** [comment]
> local addr_start = gg.getRangesList('lib.so')[0].start local addr_edit = addr_start + 0x11223344 add = {} add[1] = {} add[1].address = addr_edit add[1].flags = 4 add[1].value = 0 gg.setValues(add)
> 
> It seems that you can only hook getRangesList and return value

Btw so you app can log that ? 
![Screenshot_2024-03-26-15-52-29-060_bin mt plus](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/f1399e49-c526-4868-8cda-53ad188e42ea)
![Screenshot_2024-03-26-15-53-51-654_bin mt plus](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/afa4b7a9-98ac-458a-8ae4-dd9f5ac94b1a)

**Comment by HdShare** [comment]
In script file 1, you can output logs similar to the following, but the current version does not support it

gg.getRangesList('libil2cpp.so')
gg.setValues({
address = ,
flags = ,
value = ,
})

**Comment by QPLAYid** [comment]
> In script file 1, you can output logs similar to the following, but the current version does not support it
> 
> gg.getRangesList('libil2cpp.so') gg.setValues({ address = , flags = , value = , })

Next update you app support that right ?

**Comment by HdShare** [comment]
> Next update you app support that right ?

yes

**Comment by QPLAYid** [comment]
> > Next update you app support that right ?
> 
> yes

And  please add button copy all log / export to file .txt so i can copy all text from logs

**Comment by HdShare** [comment]
In the menu in the upper right corner of logPage, there are save and clear, but switching the interface will cause it to disappear, this bug will be fixed in the next version

**Comment by QPLAYid** [comment]
> In the menu in the upper right corner of logPage, there are save and clear, but switching the interface will cause it to disappear, this bug will be fixed in the next version

Thanks
