### ISSUE TITLE
One bug found

### ISSUE THREAD

**Issue by QPLAYid** [Xposed-Modules-Repo/me.hd.hookgg#5]
I dont check clearResult

![Screenshot_2024-03-26-17-16-32-836_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/493d92fc-4005-41f0-b94a-fd72c477db69)

Script use spam clear result

![Screenshot_2024-03-26-17-16-38-879_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/f4c402cc-ae33-4dd3-9067-c1b1db3f6527)

Btw thank for you project

**Comment by QPLAYid** [comment]
And when i scrool down hive me lagging app

**Comment by HdShare** [comment]
When you changed the functionList, did you restart the gameguardian?

**Comment by HdShare** [comment]
> And when i scrool down that give me lagging app

It might be caused by too many logs.

**Comment by QPLAYid** [comment]
> When you changed the functionList, did you restart the gameguardian?

Yes reopen gameguardian

**Comment by QPLAYid** [comment]
Need restar phone ?

**Comment by HdShare** [comment]
> Yes reopen gameguardian

No need to.

**Comment by HdShare** [comment]
> Need restar phone ?

No need to.

**Comment by HdShare** [comment]
What might the script file that triggers clearResult look like

**Comment by QPLAYid** [comment]
> What might the script file that triggers clearResult look like

I cant send file here so i upload to media fire

Here thi link script spam getclearresult

https://www.mediafire.com/file/84vootdp7iudo1x/ᴛʜᴇ+ɢʜᴏsᴛ+sᴄʀɪᴘᴛ+ᴠ1.lua/file

**Comment by QPLAYid** [comment]
![Screenshot_2024-03-26-17-34-42-285_me hd hookgg-edit](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/38d0cd68-2500-4522-9fda-a3eb1b018ed7)

On this onle detected andrees whe i search address i found but you app not give offset from addres

**Comment by HdShare** [comment]
> On this onle detected andrees whe i search address i found but you app not give offset from addres

The offset of the address cannot be unhooked from the Java layer

**Comment by HdShare** [comment]
> > What might the script file that triggers clearResult look like
> 
> I cant send file here so i upload to media fire
> 
> Here thi link script spam getclearresult
> 
> [https://www.mediafire.com/file/84vootdp7iudo1x/ᴛʜᴇ+ɢʜᴏsᴛ+sᴄʀɪᴘᴛ+ᴠ1.lua/file](https://www.mediafire.com/file/84vootdp7iudo1x/%E1%B4%9B%CA%9C%E1%B4%87+%C9%A2%CA%9C%E1%B4%8Fs%E1%B4%9B+s%E1%B4%84%CA%80%C9%AA%E1%B4%98%E1%B4%9B+%E1%B4%A01.lua/file)

Wait for me to test it out

**Comment by HdShare** [comment]
The script uses searchNumber to search for long empty strings, which causes the app to be somewhat stuttering

**Comment by QPLAYid** [comment]
> > On this onle detected andrees whe i search address i found but you app not give offset from addres
> 
> The offset of the address cannot be unhooked from the Java layer

Okay , that must munualy calculate offset from address dan header start like il2cpp that get offset , i think you app cant add feature this one ?

**Comment by QPLAYid** [comment]
> > > What might the script file that triggers clearResult look like
> > 
> > 
> > I cant send file here so i upload to media fire
> > Here thi link script spam getclearresult
> > [https://www.mediafire.com/file/84vootdp7iudo1x/ᴛʜᴇ+ɢʜᴏsᴛ+sᴄʀɪᴘᴛ+ᴠ1.lua/file](https://www.mediafire.com/file/84vootdp7iudo1x/%E1%B4%9B%CA%9C%E1%B4%87+%C9%A2%CA%9C%E1%B4%8Fs%E1%B4%9B+s%E1%B4%84%CA%80%C9%AA%E1%B4%98%E1%B4%9B+%E1%B4%A01.lua/file)
> 
> Wait for me to test it out

Okay

**Comment by QPLAYid** [comment]
> > > On this onle detected andrees whe i search address i found but you app not give offset from addres
> > 
> > 
> > The offset of the address cannot be unhooked from the Java layer
> 
> Okay , that must munualy calculate offset from address dan header start like il2cpp that get offset , i think you app cant add feature this one ?

Disbale gg,ClearResult  that not work or ?..

**Comment by HdShare** [comment]
> Okay , that must munualy calculate offset from address dan header start like il2cpp that get offset , i think you app cant add feature this one ?

There are address and getRangesList return tables that you can manually calculate the offset

**Comment by QPLAYid** [comment]
Okay

**Comment by HdShare** [comment]
> Disbale gg,ClearResult that not work or ?..

The issue with clearResults can't be determined for the time being, because I don't have a game, which causes the script to report an error

**Comment by QPLAYid** [comment]
> > Disbale gg,ClearResult that not work or ?..
> 
> The issue with clearResults can't be determined for the time being, because I don't have a game, which causes the script to report an error

https://apkcombo.com/the-ghost/com.Gameplier.TheGhost/

**Comment by HdShare** [comment]
> The script uses searchNumber to search for long empty strings, which causes the app to be somewhat stuttering

In the future, the filter anomaly parameter will be used to prevent the detection of some scripts, such as searching for empty strings with large memory

**Comment by HdShare** [comment]
![image](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/49312623/2e5c3763-1ecc-4c52-8be1-a38cb931fd6f)

When I run the script with the 101 modifier, the script throws an error

**Comment by QPLAYid** [comment]
> ![image](https://private-user-images.githubusercontent.com/49312623/316806345-2e5c3763-1ecc-4c52-8be1-a38cb931fd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDY5NzgsIm5iZiI6MTcxMTQ0NjY3OCwicGF0aCI6Ii80OTMxMjYyMy8zMTY4MDYzNDUtMmU1YzM3NjMtMWVjYy00YzUyLThiZTEtYTM4Y2I5MzFmZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5NTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxODAwNzIxNDNjNmQ3OWU0OThmMjRlYjVmN2JjYWNmMDViZGIyMjY2ODdmMTQxZTY0ZWJlYzk1MjJmYTQ2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9O5AC3x0cGlZ_k9CVgtw09D86ceblJGgGxgzjiW-Mns)
> 
> When I run the script with the 101 modifier, the script throws an error

I use gameguardian official with 101.1 version

**Comment by HdShare** [comment]
> > ![image](https://private-user-images.githubusercontent.com/49312623/316806345-2e5c3763-1ecc-4c52-8be1-a38cb931fd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDY5NzgsIm5iZiI6MTcxMTQ0NjY3OCwicGF0aCI6Ii80OTMxMjYyMy8zMTY4MDYzNDUtMmU1YzM3NjMtMWVjYy00YzUyLThiZTEtYTM4Y2I5MzFmZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5NTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxODAwNzIxNDNjNmQ3OWU0OThmMjRlYjVmN2JjYWNmMDViZGIyMjY2ODdmMTQxZTY0ZWJlYzk1MjJmYTQ2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9O5AC3x0cGlZ_k9CVgtw09D86ceblJGgGxgzjiW-Mns)
> > When I run the script with the 101 modifier, the script throws an error
> 
> I use gameguardian official with 101.1 version

My version is also 101.1 and your game architecture is 32 or 64

**Comment by HdShare** [comment]
Could it be a problem with the simulator environment?

**Comment by QPLAYid** [comment]
> Could it be a problem with the simulator environment?

Maybebecause i run realphone

**Comment by QPLAYid** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/49312623/316806345-2e5c3763-1ecc-4c52-8be1-a38cb931fd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDY5NzgsIm5iZiI6MTcxMTQ0NjY3OCwicGF0aCI6Ii80OTMxMjYyMy8zMTY4MDYzNDUtMmU1YzM3NjMtMWVjYy00YzUyLThiZTEtYTM4Y2I5MzFmZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA5NTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxODAwNzIxNDNjNmQ3OWU0OThmMjRlYjVmN2JjYWNmMDViZGIyMjY2ODdmMTQxZTY0ZWJlYzk1MjJmYTQ2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9O5AC3x0cGlZ_k9CVgtw09D86ceblJGgGxgzjiW-Mns)
> > > When I run the script with the 101 modifier, the script throws an error
> > 
> > 
> > I use gameguardian official with 101.1 version
> 
> My version is also 101.1 and your game architecture is 32 or 64

Gameguardian 64bit version

**Comment by HdShare** [comment]
It doesn't work properly on my real machine, so if you find a bug in other situations in the future, please give feedback again

**Comment by QPLAYid** [comment]
> It doesn't work properly on my real machine, so if you find a bug in other situations in the future, please give feedback again

Okay , on this one

**Comment by QPLAYid** [comment]
![Screenshot_2024-03-26-19-46-11-520_me hd hookgg-edit](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/c62480f7-2f05-4196-99f2-d69b4304a425)


File lua

https://www.mediafire.com/file/sfx2pb5nwj3ykzz/AS.lua/file

**Comment by HdShare** [comment]
> ![Screenshot_2024-03-26-19-46-11-520_me hd hookgg-edit](https://private-user-images.githubusercontent.com/102419809/316830186-c62480f7-2f05-4196-99f2-d69b4304a425.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTA0NjUsIm5iZiI6MTcxMTQ1MDE2NSwicGF0aCI6Ii8xMDI0MTk4MDkvMzE2ODMwMTg2LWM2MjQ4MGY3LTJmMDUtNDE5Ni05OWYyLWQ2OWI0MzA0YTQyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGJlOGYwOWI0ZWI2ZGNjNTM2NTFlNGMxZGM2MjI4OTNhNmM3MTJhMzhkMGMxYjI3NGQ1Y2JhYWNiNzI4NGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q5BfkpNVyeV_PuURoJEtuXLDqNob6bhOLm0eIXjm6_8)
> 
> File lua
> 
> https://www.mediafire.com/file/sfx2pb5nwj3ykzz/AS.lua/file

Coding or font issues

**Comment by HdShare** [comment]
![image](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/49312623/1a64a2df-ce44-46fa-b9b2-9bd466ff36f9)

This is due to a large number of anomalous parameters, which are filtered subsequently

**Comment by QPLAYid** [comment]
> > ![Screenshot_2024-03-26-19-46-11-520_me hd hookgg-edit](https://private-user-images.githubusercontent.com/102419809/316830186-c62480f7-2f05-4196-99f2-d69b4304a425.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTA0NjUsIm5iZiI6MTcxMTQ1MDE2NSwicGF0aCI6Ii8xMDI0MTk4MDkvMzE2ODMwMTg2LWM2MjQ4MGY3LTJmMDUtNDE5Ni05OWYyLWQ2OWI0MzA0YTQyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxMDQ5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGJlOGYwOWI0ZWI2ZGNjNTM2NTFlNGMxZGM2MjI4OTNhNmM3MTJhMzhkMGMxYjI3NGQ1Y2JhYWNiNzI4NGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q5BfkpNVyeV_PuURoJEtuXLDqNob6bhOLm0eIXjm6_8)
> > File lua
> > https://www.mediafire.com/file/sfx2pb5nwj3ykzz/AS.lua/file
> 
> Coding or font issues

Oh okay sir

**Comment by QPLAYid** [comment]
I send if i get error on you app thanks 
But can add rename apk because some lua block pacjage name apps

**Comment by HdShare** [comment]
> I send if i get error on you app thanks But can add rename apk because some lua block package name apps

Detect package name?Use MT manager to coexist directly, how most of the lua seems to be detected by gg.isPackageInstalled, and try the hook next time

**Comment by QPLAYid** [comment]
Thanks
