### ISSUE TITLE
Spam gg count

### ISSUE THREAD

**Issue by QPLAYid** [Xposed-Modules-Repo/me.hd.hookgg#6]
![Screenshot_2024-04-01-04-19-18-176_me hd hookgg-edit](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/da6ec1a9-aefe-4514-a229-919fbdc53551)

Here file 
https://www.mediafire.com/file/i8saemiuh8ca7eg/#KonzletEnc.ASR.lua/file

**Comment by HdShare** [comment]
You can close getResultsCounts
