### ISSUE TITLE
Bug app crash

### ISSUE THREAD

**Issue by QPLAYid** [Xposed-Modules-Repo/me.hd.hookgg#7]
When i try i get apo crash !

Here file 
https://www.mediafire.com/file/0wbrpiquwqftzap/Script+NadineV1+(1).lua/file

For game 
https://apkcombo.com/the-spike-volleyball/com.daerisoft.thespikerm/

Here screnshot

![Screenshot_2024-04-01-23-52-20-646_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/83ff8afc-9de6-43fd-bf96-4ecc5ee6a78a)

**Comment by QPLAYid** [comment]
Btw any update ?

**Comment by HdShare** [comment]
> Btw any update ?

It's already open source

**Comment by HdShare** [comment]
> 不，我看到不是开源的，你放弃了一些想法？

https://github.com/HdShare/HookGG
