### ISSUE TITLE
hook检测

### ISSUE THREAD

**Issue by villainousx** [Xposed-Modules-Repo/me.hd.hookgg#8]
rlgg2.0.9.2失效

**Comment by HdShare** [comment]
rlgg2.0.9.2除了那4个不能，其他应该没问题

**Comment by HdShare** [comment]
> > rlgg2.0.9.2除了那4个不能，其他应该没问题
> 
> 开启会被拉黑 这个怎么解决呀？

rlgg检测设备码或者别的，暂时不知道怎么解决，没深入研究过
