### ISSUE TITLE
Not resul seaech value

### ISSUE THREAD

**Issue by QPLAYid** [Xposed-Modules-Repo/me.hd.hookgg#9]
![Screenshot_2024-06-12-02-43-02-250_me hd hookgg](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/102419809/89e524a0-7d01-49ff-852a-128ae1fc4d94)
[SCBI_OP_Free_Script-v0.5_b-.zip](https://github.com/user-attachments/files/15792975/SCBI_OP_Free_Script-v0.5_b-.zip)

**Comment by HdShare** [comment]
I tried running the script, and it looked like it was just searching for empty strings. when I run, alert: "WARNING: Game update detected. Please download new script version."

**Comment by HdShare** [comment]
The script doesn't seem to be searching for real data, so it doesn't print out the search value

**Comment by HdShare** [comment]
> WARNING: Game update detected. Please download new script version.

At the moment it looks like it's just an empty search string with no real value and may require you to download a new script to run

**Comment by HdShare** [comment]
> I send file apk mod gg and script [GG and Script.zip](https://github.com/user-attachments/files/15856200/GG.and.Script.zip)

Try to cancel part of Hook FunctionList, This allows some of the function to be printed

**Comment by HdShare** [comment]
For example: For example, the No cooldown log is as follows:

![image](https://github.com/Xposed-Modules-Repo/me.hd.hookgg/assets/49312623/a96a855f-99af-4d61-90cd-ec27331956a6)

**Comment by HdShare** [comment]
Try turning off [addListItems] for the FuncitonList
